### ISSUE TITLE
Call same plugin twice using metalsmith.json

### ISSUE THREAD

**Issue by danigb** [metalsmith/metalsmith#129]
Currently it's no possible to call same plugin twice with different configuration usign the CLI. For example, I use metalsmith-assets to move files from different sources (that can't be on same root folder).

 What I propose is a _optional_ syntax for metalsmith.json:

```
plugins: {
  "add images": {
    "plugin": "metalsmith-assets",
    "source": "./site/images",
    "destination": "./assets"
  },
  "add css": {
    "plugin": "metalsmith-assets",
    "source": "./site/images",
    "destination": "./assets"
  }
}
```

Only when you specify the `plugin` option, the key is treated as comment (ignored).

What do you think?

**Comment by ianstormtaylor** [comment]
Ah good call. I think it actually supports arrays there, but it's what I would call a highly undocumented feature :smile_cat: Check out the bit here: https://github.com/segmentio/metalsmith/blob/master/bin/metalsmith#L144-L162

Would love a PR for docs though if that works for what you want!

**Comment by Ajedi32** [comment]
Ah, I see. So it gets normalized to an array of objects anyway: https://github.com/segmentio/metalsmith/blob/master/bin/_metalsmith#L146-L157

**Comment by Ajedi32** [comment]
Personally, I think the later format should probably be required, since JavaScript [doesn't formally guarantee object property order](http://stackoverflow.com/q/5525795/1157054), and the ordering of plugins is important in Metalsmith.

**Comment by Ajedi32** [comment]
See also: http://stackoverflow.com/q/280713/1157054

**Comment by webketje** [comment]
A sensible handling of this case would be to deprecate it in 2.4, and to remove in 3.0.
Not to be forgotten: all documentation examples should be updated
