### ISSUE TITLE
multiple pipelines?

### ISSUE THREAD

**Issue by tcurdt** [metalsmith/metalsmith#154]
As long as there is just one pipeline for e.g. blog posts everything is quite straight forward but I don't see how to have a second separate pipeline for e.g. normal webpages in the same metalsmith build.

**Comment by ericgj** [comment]
I wrote [a plugin](https://github.com/ericgj/metalsmith-branch) for that kind of thing, would likely need some adjustment to work with metalsmith 2.0.x though.

**Comment by tcurdt** [comment]
@ericgj I am trying with that right now - but even with that. You would have to have all in the same root folder to match the branches from there.

Currently struggling to split up the pipeline into various functions and not get the nesting madness.

**Comment by tcurdt** [comment]
@ericgj what am I missing here?

    function blog() {
      return function(files, metalsmith, done) {
        metalsmith
          .use(markdown())
          .use(permalinks({
            "pattern": ":date/:title",
            "date": "YYYY"
          }))
      }
    }

    metalsmith(__dirname)
      .source("content")
      .destination("./build")
      .use(branch("posts/**/*").use(blog()))

**Comment by ericgj** [comment]
Bad documentation! :sob:

I hadn't thought about grouping plugins like that. I think there are two issues:

- You need to call `done()` to signal the end of each branch-pipeline function (for it to go on to the next function in the pipeline).
```js
function blog() {
  return function(files, metalsmith, done){
     //...
     done();
  }
}
```
- The `metalsmith` object in the branch-pipeline function is actually the 'root' pipeline, not the current branch. I think this would work (but haven't tried it).  

```js
function blog() {
  return branch()   // creates a sub-branch passing down all files from the parent branch
      .use(markdown())
      .use(permalinks({
        "pattern": ":date/:title",
        "date": "YYYY"
      }));
}

metalsmith(__dirname)
  .source("content")
  .destination("./build")
  .use(branch("posts/**/*").use(blog()))
```

**Comment by tcurdt** [comment]
I did try calling `done` that didn't do it but the branch thing is - sneaky.
Will try that - thanks!

**Comment by Ajedi32** [comment]
Based on what you said in #155, I'm not really sure why you want to combine pipelines in the first place. Seems to me that there's nothing wrong with keeping separate pipelines separate. Unless there's something about your current solution that you don't like?

**Comment by tcurdt** [comment]
For example using the `browsersync` plugin with two pipelines like that is a problem.

**Comment by Ajedi32** [comment]
It seems to me that you should be able to do most of what you want using a combination of `branch` and perhaps some sort of `move` plugin. You'd have to make both the `design/` and `content/` directories subdirectories one single `source/` directory though.

**Comment by woodyrew** [comment]
@tcurdt Regarding using `browser-sync` with two pipelines.

Don't use `metalsmith-watch` or the like within your pipeline, it caused issues with various plugins. It is also good to separate the build process from watching (and triggering a re-build), the build shouldn't know anything except for what it is building.

To achieve this, use `browser-sync` and `nodemon` (or similar). 
**Nodemon** is excellent at watching files and trigger something when they've changed.
**Browser-sync** is excellent at keeping the browser state and reloading when necessary.
Combined, they work together to watch your files, rebuild and reload the browser when needed.

`package.json` scripts section:
```js
...
"main": "build.js",
"scripts": {
...
    "dev": "npm run browser_sync & nodemon --exec 'npm start && browser-sync reload'",
    "browser_sync": "browser-sync start --server site --browser=chrome",
...
},
...
```

- **browser_sync** starts `browser-sync`, serves `./site`, starts chrome as the browser
- **dev** starts browser_sync and nodemon watches the filesystem. When nodemon sees a change it will run the build script and reload the browser with the changes.

`nodemon.json`:
```js
{
 "ignore": ["site/*", "node_modules/*", "assets/*", "modules/vendor/*"],
 "ext": "js, hbs, scss, md, html, yml",
 "no_delay": "200ms"
}
```

- _**ignore**_ is what to ignore
- _**ext**_ are the extensions to watch
- _**no_delay**_ waits for a 200ms before activating the . Useful for if you change a few files at once.

To watch the files `npm run dev`.

**Comment by woodyrew** [comment]
I think this can probably be closed as it was a question about usage rather than an issue with Metalsmith. If this is not the case please re-open.
