### ISSUE TITLE
multiple pipelines

### ISSUE THREAD

**Issue by tcurdt** [metalsmith/metalsmith#155]
I currently have two different pipelines - content and assets.

    metalsmith(__dirname)
      .source("design")
      .destination("build/assets")

    metalsmith(__dirname)
      .source("content")
      .destination("build")

just because don't see another way of combining the two in one.

I looked into `metalsmith-branch` but that doesn't seem to help in this case.

What's the suggested way of handling this?

**Comment by Ajedi32** [comment]
Dup of #154
