### ISSUE TITLE
Update readme examples to metalsmith-layouts

### ISSUE THREAD

**Issue by ismay** [metalsmith/metalsmith#156]
The examples in the readme use the now deprecated metalsmith-templates. Also, the examples folder should probably be updated to metalsmith-layouts as well.

**Comment by ismay** [comment]
I've created a simple but useful boilerplate for static site generation with metalsmith that might be useful for newcomers: https://github.com/superwolff/boilerplate-in-place. Feel free to include it somewhere.

**Comment by Ajedi32** [comment]
Fixed by #182
