### ISSUE TITLE
Tests fail on Windows

### ISSUE THREAD

**Issue by Ajedi32** [metalsmith/metalsmith#158]
No idea whether you intend to support Windows or not, but in any case I thought I'd point out that the tests currently fail on Windows due to Unix-specific paths, among other things. (The first failure is here: https://github.com/segmentio/metalsmith/blob/eb43dfdb3fc7ccd5f9c7b1b501819c07cea8d162/test/index.js#L71-L74). Eh, I guess I'll spin up a Vagrant VM for now.

**Comment by Ajedi32** [comment]
The tests also seem to be sensitive to line endings, so for future reference, you might want to unset git `core.autocrlf` to ensure the fixture files are using Unix-style line endings.

**Comment by woodyrew** [comment]
I think to fix this, the tests will need converting to use `path` for generating paths and potentially using `path.sep` as a separator where necessary.
