### ISSUE TITLE
How to read YAML front-matter inside template?

### ISSUE THREAD

**Issue by fghhfg** [metalsmith/metalsmith#166]
How to pass [YAML front-matter on posts] into template?

It seems you don't need to do anything special, just type

```
---
title: aaaa
anythingYouWantVariable: bbb
---

somthing content...
```
right?

then how to read [YAML front-matter on posts] inside template?

I want to read [value of `title` and `anythingYouWantVariable`] inside template.

I still don't get it after reading #107 #112

**Comment by woodyrew** [comment]
Here's an example using handlebars:
`src/my_page.html`
```md
---
title: aaaa
template: default.hbs
anythingYouWantVariable: bbb
---

somthing content...
```
---

`templates/default.hbs`
```hbs
<html>
<head>
    <title>{{title}}</title>
</head>
<body>
    <h1>{{title}}</h1>
    <h3>{{anythingYouWantVariable}}</h3>
    <div id="content">{{{contents}}}</div>
</body>
</html>
```
---

`build.js`
```js
var metalsmith   = require('metalsmith');
var templates    = require('metalsmith-templates');

metalsmith(__dirname)
    .source('./src')
    .use(templates({
        engine   : 'handlebars'
      , directory: 'templates'
    }))
    .build(function (err) {
        'use strict';
        // For error handling
        if (err) {
            throw err;
        }
    });
```

I would recommend going through [Robin Thrift's Metalsmith Tutorials](http://www.robinthrift.com/posts/getting-to-know-metalsmith/) and if you want to know a bit more about plugins, read (my shameful self-plug) about [Metalsmith Plugins](http://www.andrewgoodricke.com/posts/2015-07-23_metalsmith_plugins.html).

**Comment by RobLoach** [comment]
Two other plugins you might want to try out are:
* [Metalsmith JSTransformers](https://github.com/robloach/metalsmith-jstransformer)
* [Metalsmith JSTransformers Layouts](https://github.com/robloach/metalsmith-jstransformer-layouts)

They work more closely with Metalsmith's content parameters, so any layout/template can have YAML front-matter. Similar to the in-place plugin, but using [JSTransformers](https://github.com/jstransformers) instead of consolidate.

**Comment by woodyrew** [comment]
This is to do with plugins rather than Metalsmith. If you're still having issue please re-open or ask a question in the [Slack Chanel](https://metalsmith-slack.herokuapp.com/).
