### ISSUE TITLE
Programattic ignoring

### ISSUE THREAD

**Issue by rstacruz** [metalsmith/metalsmith#179]
it'd be nice to use ignores that will not go through minimatch, eg:

```js
metalsmith(__dirname)
  .ignore(function (path) {
    // ignore anything that's not markdown or a file with no extension (eg, a directory)
    if (!path.match(/\.md$/) && !path.match(/\./)) {
      return true
    }
  })
```

**Comment by Ajedi32** [comment]
Metalsmith uses minimatch under the hood, so for the specific example you're using there I think this would work: `.ignore("!*.md", "!*.*")`

**Comment by tejasmanohar** [comment]
:+1: `!` patterns work just fine

**Comment by rstacruz** [comment]
I suppose for that use case, yes.

Btw, on another note, I encountered a strange thing with ignores: if you have `/` in your path spec, it compares itself against the whole absolute paths. Eg:

```js
.ignore("/Users/**/*") // will ignore everything if you have your project in /Users/yourname
```

which makes it impossible to do this:

```js
.ignore("!docs/**/*.md")
```

**Comment by Ajedi32** [comment]
@rstacruz I understand why that first one would ignore everything since it's an absolute path, but what's the problem with your second example? It looks like it should work. If it doesn't, that seems like a bug.

I'm actually not opposed to the feature you're suggesting though, since ignoring files based on their path is definitely something that needs to be in the metalsmith core for performance reasons, and even if this particular use case is met by globbing there's bound to be some situation where it wouldn't be sufficient. If one of the metalsmith maintainers confirms that they'd accept a PR adding this feature I'd be happy to work on it.

**Comment by rstacruz** [comment]
@Ajedi32: recursive-readme will check for the following paths:

```
docs
docs/foo
docs/foo/index.md
```

in this case, the 1st and 2nd will be ignored, leading the 3rd to be ignored.

**Comment by rstacruz** [comment]
also, the first one is a problem because this will not work:

```js
.ignore('docs/foo')
```

...since `/Users/rsc/myproject/docs/foo` doesn't match `docs/foo`.

**Comment by Ajedi32** [comment]
Ah, yeah that seems really messed up. The ignore option should match paths relative to the source directory, not relative to an absolute path as seems to be the case now.

This might require a few upstream fixes...

**Comment by Ajedi32** [comment]
Upstream issues:

jergason/recursive-readdir#16
jergason/recursive-readdir#23

**Comment by Ajedi32** [comment]
Or alternately we could fix this at the level of metalsmith. Doesn't seem like it would be too hard, and we'd bascially have to implement most of that functionality anyway if we want to allow functions to be passed as ignores. (Unless of course @jergason is open to having that feature implemented upstream in `recursive-readdir`).

**Comment by jergason** [comment]
I'll take a look at these recursive-readdir issues.

**Comment by Ajedi32** [comment]
@jergason Cool, let me know what you think. I might have some time to contribute a PR or two, but I want to make sure we're on the same page first before I just go ahead and start writing code.

**Comment by Ajedi32** [comment]
See also: jergason/recursive-readdir#25.
