### ISSUE TITLE
Metalsmith throw new TypeError("glob pattern string required")

### ISSUE THREAD

**Issue by aug70** [metalsmith/metalsmith#180]
I'm on node v0.12.1
First I got this error

```
Metalsmith.prototype.build = unyield(function*(){
```

and then when I downgraded to metalsmith 1.7.0
now I got this

```
throw new TypeError("glob pattern string required")
```

I want to try out Metalsmith, not very good experience so far. Still haven't been able to run the very first example!!!

Please advise how to get it running?

**Comment by Ajedi32** [comment]
Upgrading to Node 4 or io.js should fix the first problem. Not sure what's causing the second one. Seeing the full stack trace would definitely be helpful.

**Comment by woodyrew** [comment]
Could you paste the script your running? Or json file if you're using the CLI.

**Comment by quercy** [comment]
Try running your node commands with --harmony.

**Comment by Ajedi32** [comment]
Closing this issue as obsolete. Let us know if this is still something you want help with...
