### ISSUE TITLE
Non-YAML front matter support?

### ISSUE THREAD

**Issue by marcoms** [metalsmith/metalsmith#187]
Is it possible to use another format for front matter, such as JSON or TOML? One of the things that irritates me about YAML is that tabs are not permitted for indentation. Considering many developers use tabs for their code (including layouts and partials), having to switch between the two styles is not only a bit of a slowdown (editor configuration, brain power, ...) but also violates the widely accepted rule of not mixing tabs and spaces for indentationtation.
(I am aware that YAML is apparently a JSON superset, but AFAIK tabs are still banned when using JSON in YAML)

**Comment by marcoms** [comment]
I just read the gray-matter docs and it looks like you can specify different languages including JSON and TOML after the three dashes. Unfortunately I don't have access to a desktop to try this out at the moment, but if this does work with metalsmith, perhaps it would be best to clarify this in the docs? Currently the metalsmith readme only makes reference to YAML concerning front matter.

**Comment by Ajedi32** [comment]
Yeah, I noticed that as well. Quite a bit of Metalsmith's functionality is hidden away in third party libraries. It would be great if we could add docs for it, or at least refer people to the docs for the libraries Metalsmith is depending on for this functionality.

I should note that there's also a plugin I wrote, [metalsmith-matters](https://github.com/Ajedi32/metalsmith-matters) which lets you pass options gray-matter, letting you do things like change the default frontmatter format, use executable frontmatter formats like CSON and Coffeescript, change the frontmatter delimiters, etc.

**Comment by marcoms** [comment]
I agree @Ajedi32, the documentation should explain that alternative front matter formats are available.

In fact, TOML support in [gray-matter](https://github.com/jonschlinkert/gray-matter) is not actually in a working state (out of the box at least). The `toml` package is not included by default which makes the parser fail silently and return an empty object. Anyway, I've raised an [issue](https://github.com/jonschlinkert/gray-matter/issues/25) in the library, so we'll see where that goes...

For now it looks like the only way to enable TOML support is to manually install the `toml` package in your project manually.

**Comment by marcoms** [comment]
The author of gray-matter tells me that TOML not being supported by default is intentional, so the issue now is whether metalsmith will add support for these languages by adding `toml` (and optionally `coffee-script` for CSON) to `dependencies` - which will enable it in gray-matter...

**Comment by Ajedi32** [comment]
Shouldn't users who want to use TOML as their front matter format just declare the dependency themselves? I don't see any reason why metalsmith needs to include toml by default, especially when all you need to do to enable it for your site is run `npm install toml --save`. It should probably be documented though.

**Comment by marcoms** [comment]
I guess you're right - no need for unnecessary baggage.
