### ISSUE TITLE
Question: how to know the order for plugins

### ISSUE THREAD

**Issue by kud** [metalsmith/metalsmith#195]
Hello,
A noob question and probably obvious for other people but how do you know the order of plugins? 

For instance, I use `metalsmith-drafts`, how can I know where it should be placed in the queue of plugins?

**Comment by Ajedi32** [comment]
Plugins basically just make some changes to the virtual directory of files, then pass it on to the next plugin. The plugins are applied in-order from first to last. So for `metalsmith-drafts`, you want to place if after any plugins that add the `drafts: true` metadata to your files, and before any plugins that expect the drafts to already be missing (such as `metalsmith-collections`, maybe?).

**Comment by woodyrew** [comment]
Hi Kud,

Metalsmith is like a pipeline. It works sequentially through the plugins from the first to the last. Each plugin can change the state of the metadata, frontmatter, filename or the file contents. So, if one plugin relies on another, the dependency should come first.

With `metalsmith-drafts`, I would think that needs to be towards the start of your plugin pipeline.

*Something to keep in mind*: You could have a plugin in your pipeline multiple times with different parameters if needed.
