### ISSUE TITLE
Sample Request: HTML Minify Plugin

### ISSUE THREAD

**Issue by bloudraak** [metalsmith/metalsmith#203]
Provide a sample plugin that shows how to minify HTML pages using the html-minifier NPM package.

The README file needs to explain the entire process step by step. No assumption should be made that the audience is familiar with node, NPM or metalsmith.

**Comment by woodyrew** [comment]
I think this would be better as a tutorial on metalsmith.io.

https://github.com/metalsmith/awesome-metalsmith/blob/master/tutorials/js/plugins.md can be used as a starting point.

**Comment by bloudraak** [comment]
Its an excellent resource! 

We may want a repo for that plugin so we can look at the stages of development (where each state is a tag or branch). The documentation is all over the place, so this step by step documentation should be part of metalsmith.io, not on another site.

**Comment by webketje** [comment]
Closing since metalsmith already has a community html-minifier plugin. However I'm keeping the PR as it might still come in handy for documentation.
