### ISSUE TITLE
Sample Request: External Sources

### ISSUE THREAD

**Issue by bloudraak** [metalsmith/metalsmith#204]
Create a sample that shows how to read an external datasource, e.g. a JSON, YAML or XML file, and generate pages from it. Here's some examples of external sources:
- JSON file containing projects I'm working on
- XML file containing a list of computers
- ICAL feed containing a events

**Comment by wgoodall01** [comment]
Working on it. I'm making a really simple example to load a list of people into an HTML table. Got the code done, I will submit a PR when I have written some docs.
