### ISSUE TITLE
Compile Metalsmith with Babel

### ISSUE THREAD

**Issue by Ajedi32** [metalsmith/metalsmith#207]
Metalsmith currently relies on generator functions in order to function, leading to poor support for older node versions which don't support generator functions without a flag (or at all).

We might be able to fix this by compiling Metalsmith with Babel. This would solve the compatibility issues, and open the door for the use of even newer ES6 features in the core, like `async/await` (which seems like it could be a good replacement for the `co` library).

**Comment by woodyrew** [comment]
Following on from #210:

I'm pretty sure we wouldn't need to change any of the code to implement Babel. I could be wrong but I don't think it would take too long to find out.

Would we compile to the `lib/` folder or transpile on the fly? There are pros and cons for both.

**Comment by Ajedi32** [comment]
Yeah, I've thought about this a bit and I think I'm leaning towards precompiling.

Initially I thought transpiling on the fly would be more convenient, but if we do that then we'd need Babel as a runtime dependency, right? Plus I don't think it actually adds much convenience to do it on the fly, since it seems like it'd be easy to add a compile step to the Makefile to handle this.

**Comment by woodyrew** [comment]
I think the plus for on the fly would be that it would be able to take advantage of native features of whichever version of node it was using rather than dumbly always running es5 code. I'm assuming Babel does this. If not precompiled is definitely the way to go.

**Comment by Ajedi32** [comment]
@woodyrew Yeah, I don't really know enough to say for sure, but it doesn't look to me like it's that smart: https://github.com/babel/babel/blob/master/packages/babel-register/src/node.js

**Comment by woodyrew** [comment]
Let's precompile to `lib/`. It can always be converted in the future.

**Comment by Ajedi32** [comment]
@woodyrew Yeah, I'm fine with any implementation initially. Smaller optimizations like "only compile what you need to" are a secondary concern.

Looks like it is actually doable though:

https://github.com/hax/babel-features
https://github.com/ariporad/babel-preset-features

**Comment by ben-eb** [comment]
:+1: for pre-compiled.

https://travis-ci.org/ben-eb/metalsmith-mdast/jobs/101096785

**Comment by ben-eb** [comment]
Ran into this again. Any updates?

https://travis-ci.org/ben-eb/metalsmith-remark/jobs/101096785

**Comment by Ajedi32** [comment]
@ben-eb See the related PR referenced above.

**Comment by ben-eb** [comment]
Awesome! :smile:

**Comment by Zearin** [comment]
Node v7 just came out.  I think it’s pretty safe to drop v4.  :-)

**Comment by Zearin** [comment]
Also, I think reading and writing Metalsmith in modern ES6 syntax will be a big win for maintenance.  

Happy maintenance == happy program == happy users!

**Comment by Ajedi32** [comment]
If we're following the [Node LTS release schedule](https://github.com/nodejs/LTS), Node v4 doesn't get dropped until April 2018:

![Node Long Term Support Release Schedule](https://raw.githubusercontent.com/nodejs/LTS/master/schedule.png)

Looks like we can drop v0.10 now though if we want. See #231

**Comment by hollowdoor** [comment]
Might I humbly suggest rollup for this? http://rollupjs.org/guide/#using-rollup-with-babel

Scroll to the bottom of this page https://github.com/rollup/rollup/wiki/Command-Line-Interface to see how to output multiple bundles. For metalsmith a commonjs, and es6/es2015 build would probably be best.

If not that's alright. It's also another thing that has to be learned. In my experience it works quite well though. rollup is mostly good for the static module syntax. And also easier support for both pre-build, and user transpilation.

**Comment by webketje** [comment]
The features required for metalsmith work natively in all Node versions, no point in using a compilation step now the ecosystem has caught up :)
