### ISSUE TITLE
Issue serving SVG

### ISSUE THREAD

**Issue by AdrieanKhisbe** [metalsmith/metalsmith#209]
Can't serve svg images. 

Current error is:

<img width="841" alt="capture d ecran 2016-01-07 15 45 32" src="https://cloud.githubusercontent.com/assets/2601132/12173247/f80393b0-b555-11e5-96f9-f737cd6b1cda.png">

> This page contains the following errors:
> error on line 16 at column 10: Opening and ending tag mismatch: link line 0 and head
> Below is a rendering of the page up to the first error.

Real example:
http://senecajs.org/images/tcs-logo.svg

Versions: metalsmith 2.1.0
Full deps: https://github.com/senecajs/senecajs.org/blob/master/package.json#L32-L44

**Comment by Ajedi32** [comment]
This seems very unlikely to be a problem with the Metalsmith core, as Metalsmith actually knows nothing about HTML or SVG.

If I had to guess, I'd say this is probably caused by `metalsmith-layouts` trying to process the SVG file as HTML.

Maybe try using the [pattern](https://github.com/superwolff/metalsmith-layouts#pattern) option to exclude SVG files from your layout...

**Comment by AdrieanKhisbe** [comment]
thanks @Ajedi32, will try that!

**Comment by AdrieanKhisbe** [comment]
indeed, problem is because of layouts having a default.
will see how to negate a pattern

**Comment by Ajedi32** [comment]
I'd probably specify a whitelist like `*.md`. It seems likely to me that other files like CSS might also suffer from this issue.

If you'd prefer to just blacklist SVG's though, I'm pretty sure the syntax is `!*.svg`.

**Comment by AdrieanKhisbe** [comment]
I just specify to apply to `pages` in our case.

Thanks @Ajedi32 for your tips :)

**Comment by woodyrew** [comment]
Also, consider having your assets outside of your `source` directory and bring them in with something like `metalsmith-assets`.

**Comment by AdrieanKhisbe** [comment]
mmmmm. Interesting, very interesting!
Thanks for the tip @woodyrew
