### ISSUE TITLE
Gracefully handle .build() being called with no arguments

### ISSUE THREAD

**Issue by Ajedi32** [metalsmith/metalsmith#211]
Apparently, at the moment if you call `.build()` with no arguments, the build fails silently. This is very confusing behavior. See #133, #92. This should be fixed. (Either by failing with an error message that makes it clear what went wrong, or by providing a sane default value for the callback.)

**Comment by woodyrew** [comment]
@Ajedi32 I'm not sure this is possible with `unyield`.
- If a callback is provided it runs the callback.
- If **no callback** is provided it returns a generator function which should be `yield`.
The problem occurs when it's not passed a callback and doesn't get `yield`.

I don't see how we can fix this situation without breaking existing functionality (at least using generators). I think we could have similar behaviour with Promises and they still run without `.then()`. 

Not sure how much work this would be?

**Comment by Ajedi32** [comment]
Yeah, that's a good point. I think what we really want to do here is switch to Promises, as those are already  handled in a more graceful way by modern browsers:

![Uncaught (in promise) asdf](https://cloud.githubusercontent.com/assets/1876931/18054333/05aba4d6-6dc9-11e6-9a08-498c7a921e67.png)

**Comment by Ajedi32** [comment]
Ah, so it seems that while Node doesn't support reporting unhandled promises by default, it does provide a way for you to handle them yourself:

```text
vagrant@ubuntu-1404:~$ nvm install 4
Downloading https://nodejs.org/dist/v4.5.0/node-v4.5.0-linux-x64.tar.xz...
######################################################################## 100.0%
Now using node v4.5.0 (npm v2.15.9)
vagrant@ubuntu-1404:~$ node
> process.on('unhandledRejection', (reason, promise) => console.log("Error, unhandled promise '" + promise + "':" + reason));
...
> var x = new Promise(function(accept, reject){ reject("asdf"); })
undefined
> Error, unhandled promise '[object Object]':asdf
```

**Comment by woodyrew** [comment]
The difference with the promises is that they will still run the build even if the promise isn't processed with `.then()`, etc, and I agree with the `unhandledRejection` :+1: 

It would be good to use `Bluebird` as native promises aren't as efficient plus it will probably provide some useful functionality.

Point 2. switch should probably be called `silent(true)` 

Changed the milestone issues.
I'll have a go when I get a moment.

**Comment by Ajedi32** [comment]
Does `unhandledRejection` work with Bluebird?

And yeah, `silent` seems like a good choice for that option.

**Comment by woodyrew** [comment]
Yes, it appears so but I'll test it out. Only bad thing about Bluebird is the docs but we (Metalsmith) aren't much better. :disappointed:
