### ISSUE TITLE
Include file.type in file metadata?

### ISSUE THREAD

**Issue by cameronjroe** [metalsmith/metalsmith#217]
Currently, I'm seeing people are checking the file type for specific transformations. What if metalsmith included a `file.type` property that identified the type of file or simply returned null if not found. This would help developers avoid regexing and allow them to test the file type with something like `file.type == html` or `file.type == md`. Not sure if this would be a good idea in terms of performance, but I thought I'd mention it.

**Comment by Ajedi32** [comment]
By "type" you mean the file extension? As I understand it, this has the same problems as #58. It requires adding special attributes to the file objects which need to remain in-sync between plugin calls.

For example, let's say I wrote a plugin that strips the file extensions out of the names of all `.md` files. What would `.type` return when I call it in a plugin further in the chain, and how would that be implemented?

**Comment by cameronjroe** [comment]
Maybe there's a private property that doesn't get touched `file._type`?

**Comment by Ajedi32** [comment]
@cameronjroe Sorry, let me try making that example more concrete.

Let's say I read in a directory containing one file:

```javascript
{
  "path/to/file.md": {
    "contents": "Some contents",
    "_type": "md"
  }
}
```

Now I run it through a plugin that renames the file:

```javascript
function plugin() {
  return function(files) {
    files["path/to/file"] = files["path/to/file.md"];
    delete files["path/to/file.md"];
  }
}
```

What should the files object look like for the following plugin?

If `_type` is still `md`, why? The file is no longer an `md` file. If `_type` should be something other than `"md"`, how should that be implemented?

**Comment by cameronjroe** [comment]
If a file is deleted they technically it doesn't exist, so `file._type` should be removed or set to `null`.

**Comment by Ajedi32** [comment]
@cameronjroe That code doesn't delete the file though, just move it. What about this?

```javascript
function plugin() {
  return function(files) {
    files["path/to/file"] = files["path/to/file.md"];
  }
}
```

Now we're just copying the file object to another path. What should happen here? Does Metalsmith need to detect that the file object exists at two different paths and make a shallow copy?

My point is, this adds a significant amount of complexity to the implementation of Metalsmith for not a lot of value. You can already get the file type by calling [`path.extname(path)`](https://nodejs.org/api/path.html#path_path_extname_p), and convenience attributes like what you're proposing can always be implemented with a plugin.

Why do you think this needs to be in the core?

**Comment by cameronjroe** [comment]
I see your point. In that case, I agree with you and would probably just use a plugin. Thanks for clarifying.

**Comment by Ajedi32** [comment]
No problem. FYI, I think the simplest implementation of the plugin you want is:

```javascript
var each = require('metalsmith-each');
var path = require('path');
function addTypeProperty(){
  return each(function(file, filePath){
    file["_type"] = path.extname(filePath);
  });
}
```

It'd probably need to be a bit more complex if you want it to handle cases like the copy example I wrote above, but that's the gist of it.
