### ISSUE TITLE
Sample Request: Multiple blogs + static pages

### ISSUE THREAD

**Issue by zslabs** [metalsmith/metalsmith#225]
Hi all,
Really impressed with what I'm seeing with Metalsmith so far! I'm having a bit of trouble wrapping my head around creating a site that would have multiple different blogs, with different sources and params along with any other static pages that would be run through Handlebars partials + layouts.

Know that's a bit of a run-on feature-list, but think a quick example would be very helpful in more complex setups. Not sure if this would be different pipes or if everything can be done in one, monolithic stream.

If it's of any context; I'd be aiming to do this with `gulpsmith`, but the basic example within a Metalsmith setup would be just as good. Thanks so much!

**Comment by woodyrew** [comment]
You can do it within the same Metalsmith pipeline depending how complicated the differences are. Have you had a look at `metalsmith-collections`? This should get you going. The slack channel is pretty good for getting pointers.

**Comment by zslabs** [comment]
Thanks @woodyrew I'll check out the slack channel and post back any findings.

**Comment by zslabs** [comment]
Ah, yes `metalsmith-collections` is the way to go. Thanks!
