### ISSUE TITLE
variable content slides on homepage, how?

### ISSUE THREAD

**Issue by sandrodz** [metalsmith/metalsmith#227]
How would you implement something like this in metalsmith?

Problem 1:
I've N amount of slides on homepage. Each slide can contain N amount of Posts.
I want to manually control N amount of slides, and posts that are displayed there.

Problem 2:
Post featured image.

**Comment by Ajedi32** [comment]
It sounds to me like you're imagining Metalsmith to be a much higher-level library than it is. Metalsmith isn't a UI framework; it's a static site generator.

You implement a carousel in Metalsmith the same way you would on any website: by writing the necessary HTML/CSS/JavaScript yourself, or by using an existing library that does it for you. ([Slick](http://kenwheeler.github.io/slick/) was the first example of such a library that appeared when I Googled it.)

**Comment by sandrodz** [comment]
Hey, thanks for the reply but that is not what im asking. I aleeady have frontend, im using metalsmith as "backend" if it can be called that :) simplest solution that comes to mind is creating a custom object with parameter link / title / thumb than loop over it in tempkate file and display my slider, but there surely is a better way right?

**Comment by Ajedi32** [comment]
I'm still not quite sure what you're asking. What plugins are you currently using? [metalsmith-collections](https://github.com/segmentio/metalsmith-collections) should allow accessing a list of "posts" through the global metadata if that's what you're looking for...

**Comment by sandrodz** [comment]
I'm using quite a lot of plugins actually, including collections.

```
var Metalsmith  = require('metalsmith');
var templates   = require('metalsmith-react-templates');
var assets      = require('metalsmith-assets');
var markdown    = require('metalsmith-markdown');
var publish     = require('metalsmith-publish');
var collections = require('metalsmith-collections');
var ignore      = require('metalsmith-ignore');
var permalinks  = require('metalsmith-permalinks');
var paths       = require('metalsmith-paths');
var serve       = require('metalsmith-serve');
//var watch       = require('metalsmith-watch');

Metalsmith(__dirname)
  .source('content')
  .destination('build')
  .clean(true)
  .use(ignore([
    'articles/.*',
    'projects/.*'
  ]))
  .use(publish())
  .use(collections({
    pages: '*.md',
    articles: {
      pattern: 'articles/*.md',
      sortBy: 'date',
      reverse: true
    },
    projects: 'projects/**/*.md'
  }))
  .use(markdown())
  .use(permalinks())
  .use(paths({
    property: "paths"
  }))
  .use(templates({
    directory: 'templates',
    isStatic: true
  }))
  .use(assets({
    source: 'public'
  }))
  .use(serve())
  //.use(watch({
  //  paths: {
  //    "${source}/**/*": "**/*",
  //    "templates/**/*": "**/*"
  //  },
  //  livereload: false
  //}))
  .build(function(err) {
    if (err) throw err;
  });

```

I want to display articles and projects on my slider.

slide1:article1,article2,project6
slide2:project1:project2,project5,article3

What I would do in traditional backend programming is create a table (Entity–attribute–value model) with col1=key/col2=value combination, key would be a slide1 slide2 names, and value would be a serialised list of article ids. Than in template I'd run foreach on those and display slides and slide content.

I don't know how to deal with this type of data in metalsmith. I don't know following:

1. where how to save my `{slide1: [article1,article2,project6]}`
2. how to 'query' for article1 article2 project6 - obviously I don't want to create manual object/array combinations.

this is the best I can do. sorry if my explanation is not great.

**Comment by Ajedi32** [comment]
This sounds like something you may want to use a custom plugin for. You can "query" for projects by accessing the `projects` attribute in the global metadata, then build your slides object from that.

Here's an article on writing plugins for Metalsmith. If you're already familiar with JavaScript the process is actually pretty straightforward: http://www.andrewgoodricke.com/blog/metalsmith-plugins/

**Comment by webketje** [comment]
Closing as stale and since this would rather be a support question for Stackoverflow or the Gitter chat.
