### ISSUE TITLE
Drop support for older Node versions

### ISSUE THREAD

**Issue by RobLoach** [metalsmith/metalsmith#231]
[Node 4.0.0 (Stable)](https://nodejs.org/en/blog/release/v4.0.0/) was released in September, 2015. The long-term-support release of Node (currently latest is [Node 4.4.1](https://nodejs.org/en/blog/release/v4.4.1/)) is out, and brings a lot of new changes. There are loop-holes taken to support Node 0.10 and 0.12 which cause [code-bloat](https://en.wikipedia.org/wiki/Code_bloat), and unneeded complexity. Adopting Node 4 in a [new major branch (`3.x`)](http://semver.org/) of Metalsmith will:
- Remove the loop holes for Node 0.10/0.12
- Clean up the source
- Allow adopting some of the newer features of Node
- Pave a nice pathway for [some ES6 adoption](https://github.com/metalsmith/metalsmith/pull/214)
- Use Promises for some of our async stuff

**Comment by RobLoach** [comment]
Using [semver](http://semver.org/) and opening up a new branch means we don't have to be held back by the Node release schedule. Metalsmith 3.x can target Node 4, while people on Node 0.10/0.12 can still target Metalsmith 2.x.

**Comment by woodyrew** [comment]
@RobLoach Node 0.10 is no longer supported with `v2.x` of Metalsmith anyway.

We could create a long serving branch for `v3.x` until December 2016 when Node `v0.12` is no longer supported. Node `v4` functionality should be the baseline for this version though.

**Comment by Ajedi32** [comment]
Is there any particular functionality specific to Node v4 that you're planning on using? I'm fine for dropping support for older node versions if needed, but I also see no reason to drop support simply for the sake of dropping support. If we _can_ support older Node versions without that being too much of a headache, why not?

**Comment by woodyrew** [comment]
Apart from generator functions without flags, I think most of the >ES5 features that are useful are in ([Node v4 highlights](http://www.cli-nerd.com/2015/09/09/7-reasons-to-upgrade-to-node-v4-now.html)). Async/Await is just syntactic sugar around generators and can be used with **co** or **bluebird** until it's native.

By the end of the year, we won't need Babel. Not sure it's worth adding for a few months to then remove it. I wonder what Node versions people are running anyway?

**Comment by Ajedi32** [comment]
Sure async/await is mostly just syntactic sugar, but so are most of the other features in ES6-7. (Classes, arrow functions, object literals, etc.) It's still nice to have. Also, Babel gets us way more than just async/await. Node 4 also does not support default parameters, rest parameters, the spread operator, or object destructuring by default. See: http://kangax.github.io/compat-table/es6/#node4

It'll be quite some time before support for Node 4 gets dropped and we're able to use those features. Why wait when we can just use Babel?

I guess it really just depends on how difficult Babel turns out to be to get set up. I've been meaning to have a crack at that myself for some time now, but I haven't really found the time yet.

**Comment by ismay** [comment]
I'd be for dropping support for node < 4. I'm already using es6 with babel for [metalsmith-in-place](https://github.com/superwolff/metalsmith-in-place), but eslint won't run on older node versions.

Which means that it's not easy to add it to my travis build, and that PR's won't automatically be checked against my linting rules. Which would be a great feature to have. Anyway, rather specific use-case, but I'd be in favor of dropping.

**Comment by Ajedi32** [comment]
Yes, as of December of last year Node 0.12 has been EOL'd, so I'm now fine with dropping it.

Note also that Metalsmith plugins are under no obligation to support all of the same Node versions that Metalsmith core does. If you want to drop support for Node 0.12 (or any other Node version) in metalsmith-in-place you're free to do so at your own discretion.

**Comment by webketje** [comment]
Repurposed for current context
