### ISSUE TITLE
jekyll example "npm run build" fails

### ISSUE THREAD

**Issue by MortalCatalyst** [metalsmith/metalsmith#233]
I cloned latest example and completed npm install successfully.

However npm run build errors.

```bash
sayth@sayth-E6410:~/Projects/metalsmith/examples/static-site$ npm run build
npm ERR! Linux 4.4.0-16-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3

npm ERR! missing script: build
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sayth/Projects/metalsmith/examples/static-site/npm-debug.log
sayth@sayth-E6410:~/Projects/metalsmith/examples/static-site$ 
```

**Comment by MortalCatalyst** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.8.3
3 info using node@v5.10.1
4 verbose stack Error: missing script: build
4 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:147:19)
4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:57:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:232:12
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:414:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
5 verbose cwd /home/sayth/Projects/metalsmith/examples/static-site
6 error Linux 4.4.0-16-generic
7 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
8 error node v5.10.1
9 error npm  v3.8.3
10 error missing script: build
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by Ajedi32** [comment]
> `sayth@sayth-E6410:~/Projects/metalsmith/examples/static-site$ npm run build`

This isn't the Jekyll example you're running, it's the static-site example. The README for that example states:

> This example uses Metalsmith to make a static site. To test it out yourself just run:
> 
> ```
> $ make build
> ```
