### ISSUE TITLE
proposal - source use another metalsmith `files` object

### ISSUE THREAD

**Issue by futurist** [metalsmith/metalsmith#234]
It's better to have 

- `metalsmith()` use `files` object from another `metalsmith`, now it's only accept `string` type.
- even better if it can joint multiple parameters of different types.

It's important for the scenarios that require `pre-build` for the source, e.g. build **header** and **footer** `partials` from database on  the fly, etc., to avoid writing temp files into disk.

Please consider and evaluate this feature.

**Comment by Ajedi32** [comment]
Hmm. I'm a little confused about the use case for this. This sounds a bit similar to #154, perhaps?

Why not just use a single call to Metalsmith and include everything you need in that single pipeline? Build the header and footer first, then apply later transformations with additional plugins.

**Comment by danhalliday** [comment]
I have another use case for this.

- A site with some `.md` page which are processed easily enough with a simple layout
- Lots of `.md` page inside NPM in `node_modules` which I want to pull in to the site
- I want to use the metadata of the pages from `node_modules` to build navigation in the main site

I think the way to do this at the moment would be an initial copy step to move everything to one place and process with Metalsmith from there.

**Comment by woodyrew** [comment]
@danhalliday You can achieve this with a plugin to get all the information you need from `node_modules`.

**Comment by woodyrew** [comment]
@futurist Did Ajedi32 answer your question — can this be closed?

**Comment by futurist** [comment]
though it's not 100% solution, but can be a way. Can be closed and I'll try in later project, if any problem will feedback here again. Thank you!
