### ISSUE TITLE
Modular pages ?

### ISSUE THREAD

**Issue by eightyfive** [metalsmith/metalsmith#238]
Hi there,

Is it possible with Metalsmith to achieve something in the fashion of "Grav Modular pages":
https://learn.getgrav.org/content/modular

Your page is basically broken into multiple children sub-pages (`.md + .hbs` each). It makes a lot of sense for homepage of marketing websites for example, where design/html is not monolithic (cannot be translated from a simple `.md` straight away).

More generally, is there a way to share content (`.md`) accross pages? Is it possible to use `src/content/posts/my-post.md` in a place/page not related to its direct template (for ex: you want to display an excerpt on any page)?

Ok, that's two questions... Cheers.

**Comment by Ajedi32** [comment]
Looks like its just concatinating pages together based on the contents of a `modular.md` file? Sure, you can do that, though you'd likely have a write a plugin for it.

As for the general concept of sharing content between pages, I guess [`metalsmith-layouts`](https://www.npmjs.com/package/metalsmith-layouts) `partials` feature might be close to what you want?

**Comment by eightyfive** [comment]
Thanks for the reply. So there is no existing Plugin doing so, ok.

As per the general concept of sharing content between pages, I believe this is not exactly what I am looking for.

What I am looking for is almost an "ORM" for the content:

```
var someOtherPage = Content.find('products/product-01');
//
{{ someOtherPage.header.title }};
{{{ someOtherPage.contents }}};
...
```

In that way, there is the possibility to decorrelate the content 100% from its (default) Layout.

I understand this is not the main use case for metalsmith. But that would be handy. I'm closing the issue, thanks.

**Comment by Ajedi32** [comment]
Yeah, the Metalsmith core is pretty minimal. It's definitely possible to create a plugin that does that, but to my knowledge no such plugin currently exists.
