### ISSUE TITLE
Side effects when setting global metadata

### ISSUE THREAD

**Issue by maiertech** [metalsmith/metalsmith#247]
This is an issue I noticed when using [`metalsmith-collections`](https://github.com/segmentio/metalsmith-collections), [`metalsmith-tags`](https://github.com/totocaster/metalsmith-tags) and [`metalsmith-permalinks`](https://github.com/segmentio/metalsmith-permalinks) together (in this sequence).

`metalsmith-permalinks` adds a `path` variable to each file in `files`. Because the objects from `files` are also linked in the collections in `_metadata`, I should be able to access `path` in layouts when iterating through collections. This is the case as long as I do not use `metalsmith-tags`.

When using `metalsmith-tags`, I can see in the debugger that `metalsmith-permalinks` still adds `path` to each file in `files`. But `path` does not show up in the collections in `_metadata`. Which made me think that the objects in `files` are not the same as in the collections any more.

And indeed, `metalsmith-tags` gets the metadata via `metadata()`, adds the global `tags` and sets them via `metadata()` (see https://github.com/totocaster/metalsmith-tags/blob/99837b4ec0b0c8a5f897b9be62cd22d184dfb935/lib/index.js#L195). And that's where a deep clone happens: https://github.com/metalsmith/metalsmith/blob/c24385888bc9dd05d8d1714cda9c63bba949ab73/lib/index.js#L86. And from now on, `files` and collections in `_metadata` are not using the same objects any longer.

And since `metalsmith-permalinks` comes after `metalsmith-tags` the `path` attribute makes it into each file in `files`, but not into the collections. And whenever I'm trying to access `path` in collections in a layout, there is not `path` there.

The question is: should `metadata()` clone (both for get and set) or should plugins have unrestricted access to `_metadata`?

**Comment by Ajedi32** [comment]
That's a really interesting problem, thanks for bringing this up. I agree this behavior seems rather inconsistent and should probably be changed.

As for what to change it to, currently I'm leaning towards not cloning the object at all (either when accessing or updating the metadata). There a few reasons for this:

1. While at first glance allowing mutations to the object returned from/passed to `metalsmith()` to affect the global metadata seems like confusing behavior, this is actually a fairly common property of languages like JavaScript, Ruby, and (I believe) Python. 
2. Requiring a deep clone every time global metadata is accessed seems like it could be a potential performance problem on sites which utilize global metadata extensively. (Though I haven't tested this.)
3. Many existing, popular plugins (such as metalsmith-collections) rely on the ability to mutate the global metadata returned by `metadata()` in this way.

**Comment by mdotasia** [comment]
I agree. I also looked at a few popular plugins and they all seem to mutate global metadata and not use the setter to write it back like metalsmith-tags does. I think we need a documentation on how to write plugins and mention this.

I have not yet come me to a conclusion whether or not global metadata mutation is a good thing or not. In any case, crucial plugins seem to rely on it so for the time being anything else would break too much.

**Comment by woodyrew** [comment]
This is interesting. Metadata is always mutated within plugins with the exception of `metalsmith-tags` as far as my experience goes.

Is the issue resolved when the following is removed from `metalsmith-tags`?
```js
// update metadata
if (!opts.skipMetadata) {
    metalsmith.metadata(metadata);
}
```

**Comment by mdotasia** [comment]
It does in principle. Removing above lines breaks the tests so I had touch a few more things to make the tests run. See https://github.com/totocaster/metalsmith-tags/pull/37.

**Comment by webketje** [comment]
Throughout metalsmith objects are mutated by reference and most of the ecosystem *depends on not using the metalsmith.metadata({ ... }) setter in plugins*. I understand the `clone` is there so that the initial `.metadata({ ... })` (run by a user as part of the build & not in a plugin) would not alter the data passed to it in a situation like this:

```js
class Options {
  constructor() {
    this.someProp = 'a'
  }
  toJSON() {
    return JSON.stringify(this)
  }
}

const options = new Options()

Metalsmith(__dirname)
  .metadata(options)
  .use((files, metalsmith) => {
    metalsmith.metadata().toJSON= 'overwritten'
  })
  .build((err) => {
    console.log(options.toJSON()) // -> error options.toJSON is not a function
  })
```

However I would argue passing a class instance used elsewhere to Metalsmith is a rare use case, and one that is never demonstrated in the docs, and it should be supposed that if a developer does pass, eg a class instance as above, it was done intentionally. Having a reference to metadata outside of the metalsmith build can be considered a feature rather than a bug.

So there's 2 things to do to handle this:

* the `clone`  should definitely be removed
* the `metadata` setter should `Object.assign` rather than replace `this._metadata`
