### ISSUE TITLE
Slack channel is down

### ISSUE THREAD

**Issue by cmoulliard** [metalsmith/metalsmith#248]
The slack / channel web site is down - http://metalsmith-slack.herokuapp.com/

```
Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.
```

**Comment by Ajedi32** [comment]
@lambtron can you take a look at this? I don't have access to the Heroku site.

**Comment by woodyrew** [comment]
@cmoulliard I believe you can use this link now also: https://metalsmith.slack.com/signup let me know if this works for you please?

@Ajedi32 If the build in slack signup works I'll convert all the instances of the signup that I'm aware of:

- metalsmith.io banner & content
- metalsmith github page
- awesome metalsmith github page

Let me know if I've missed any that you can think of.

**Comment by cmoulliard** [comment]
I can't signup here (https://metalsmith.slack.com/signup) as I don't have an email address under @segment.com

**Comment by woodyrew** [comment]
@cmoulliard thanks, I'll poke @lambtron to fix :smile:

**Comment by lambtron** [comment]
Sorry about that!! My heroku free dynos were exhausted for this month. I just upgraded it and now it works! Thank you for letting me know.
