### ISSUE TITLE
Getting 'ENFILE: file table overflow' when building

### ISSUE THREAD

**Issue by johanbrook** [metalsmith/metalsmith#257]
Hi!

I'm getting this in my build step at [my site](https://github.com/johanbrook/johanbrook.com/) using Metalsmith 2.2.0:

```
[01:39:18] Using gulpfile ~/Sites/johanbrook.com/gulpfile.js
[01:39:18] Starting 'build'...
[01:39:18] Finished 'build' after 6.2 ms
✘ Failed to read the file at: /Users/Johan/Sites/johanbrook.com/src/posts/2013-03-12-programming-communication.md

ENFILE: file table overflow, open '/Users/Johan/Sites/johanbrook.com/src/posts/2013-03-12-programming-communication.md'.
```

I'm using `concurrency()` and I've tried with various values, ranging from 1 to 100 000, but to no avail. Any idea what might cause this?

**Comment by woodyrew** [comment]
Does the build fail when calling directly with `node build.js` or only when calling with gulp?

**Comment by johanbrook** [comment]
I'm gonna close this guy for now, since it might've been a problem locally on my side: that I needed to increase the open file limit (http://blog.mact.me/2014/10/22/yosemite-upgrade-changes-open-file-limit). I don't think it was Metalsmith per se that is to blame.

**Comment by Ajedi32** [comment]
That's still pretty odd, as Metalsmith shouldn't have _that_ many files open at once (especially if you have `concurrency` set to a low value)...

**Comment by johanbrook** [comment]
Yep, indeed. Although, the concurrency limit was specifically for the EMFILE error, no? https://github.com/metalsmith/metalsmith/issues/65

**Comment by Ajedi32** [comment]
They're very similar errors. See https://www.gnu.org/software/libc/manual/html_node/Error-Codes.html

EMFILE is for too many open files in the current process. ENFILE is for too many open files on the entire system. I suppose the latter error could be caused by some other process on your system besides Metalsmith having too many files open, so maybe this _isn't_ an issue with Metalsmith.

**Comment by johanbrook** [comment]
Makes sense. I got the error while working with Meteor the other day too (which is crunching and rebuilding files as well).

**Comment by woodyrew** [comment]
I have sometimes had `ENFILE` when _watching_ too many files and running Metalsmith - Not Metalsmith's fault.
