### ISSUE TITLE
NPM's metalsmith versions differ from github (recursive-readdir version)

### ISSUE THREAD

**Issue by sigo** [metalsmith/metalsmith#268]
I've installed `metalsmith` package via npm. The latest version is `2.2.2`.

- First question/note: I don't see tag or release with this number [at the github](https://github.com/metalsmith/metalsmith/tags).
- Second question/note: version before (2.2.1) contains `recursive-readdir` [at ^2.1.0](https://github.com/metalsmith/metalsmith/blob/v2.2.1/package.json#L24), but my locally installed metalsmith at `2.2.2` contains `recursive-readdir` at `^1.3.0` (see below).

<img width="781" alt="screen shot 2016-11-03 at 19 57 09" src="https://cloud.githubusercontent.com/assets/321881/19980802/c193a8a0-a1ff-11e6-812e-0a1260db74c0.png">

Do I don't understand something? Maybe should I install `metalsmith` directly from github?

Additionaly, I see that should be [already fixed in `2.1.0` by @wdullaer pull request](https://github.com/metalsmith/metalsmith/pull/258/commits/3cf4daecc190576033e47b33a2829deb6a59bb2e).

**Comment by Ajedi32** [comment]
See #261, #262.

@woodyrew, did you ever push the new 2.3.0 release to NPM? Also, it looks like there's no `v2.2.2` tag in the repo right now?

**Comment by woodyrew** [comment]
Yes, I think it's the latest tag, as `2.2.2` was releases after `2.3.0`, I'll publish the latter again to make it the _latest_.

**Comment by woodyrew** [comment]
Set `2.3.0` with the tag `latest`. Correct on npm now.

**Comment by Ajedi32** [comment]
Cool. Can you tag `v2.2.2` with the appropriate revision in git? There isn't one on GitHub right now. https://github.com/metalsmith/metalsmith/tags

**Comment by woodyrew** [comment]
`v2.2.2` was tagged but they were not pushed. Sorry about that.

@sigo The [Change Log](https://github.com/metalsmith/metalsmith/blob/master/CHANGELOG.md#change-log) should explain things. Sorry for any confusion.
