### ISSUE TITLE
Serious question: do each plugins have its own way of pattern matching?

### ISSUE THREAD

**Issue by bitinn** [metalsmith/metalsmith#273]
(I could have asked this in Slack, but I want this issue to exist so it's searchable via Google.)

I am new to Metalsmith, but certainly not new to Node.js, and one major problem I have with it is: **How do each plugin filter the file list, so that they don't accidentally process files that they don't handle?**

When I have only markdown files in source folder, everything is fine. But as soon as I put other files in that folder (or in a sub-folder), I start to get errors like:

`Error: [metalsmith-sass] Error: Invalid CSS after "<": expected 1 selector or at-rule, was "<!DOCTYPE html><htm" -> /Users/df/git/mysite.com/src/scss/site.scss:1:1`

This error message is really frustrating:

- My `site.scss` at source folder doesn't contain `<!DOCTYPE html>` at all. So it means some other plugins have touched my file, but I can't see which one immediately.
- Turns out it was `metalsmith-layouts`, but it uses `layouts` folder by default, why is it touching the files in source folder?
- `metalsmith-layouts` supports `pattern`, but matching from where? source folder? layout folders? current working directory?

Can you see why this is unnecessary difficult even for experienced developers?

I know, architecture can't be changed in one day, and nobody is being payed to do this. But here I am, hoping Metalsmith can lean close to [Koa](https://github.com/koajs/koa) way of middleware handling one day.

Wish you all well :)

**Comment by hollowdoor** [comment]
pattern is for matching file names contained in the source folder. I don't know about each plugin having it's own pattern. I suppose so because there's nothing limiting that. It's unlike gulp where the pattern is used in the core of the module.

**Comment by bitinn** [comment]
@hollowdoor Thx for the reply, could I ask you a question? How can I prevent a file from being processed by a plugin (not all plugins), reliably and consistently?

Say, I only want `metalsmith-markdown` to know about `.md` files, and `metalsmith-layouts` to know about `.template` files, and `metalsmith-sass` to know about `.scss` files.

Is it possible? I read both `ignore()` and `metalsmith-filter`, they seem like an exclude/include filter for all plugins (modify the global file list), not individual plugins.

**Comment by bitinn** [comment]
So it looks like I need this to get `metalsmith-layout` to work with my marko templates and output from markdown plugin (html only):

```
		.use(layouts({
			engine: 'marko'
			, 'default': 'base.marko'
			, pattern: '**/*.html'
		}))
```

**Comment by woodyrew** [comment]
@bitinn Each plugin has access to all files within the source directory. However most plugins will take a pattern to limit their scope to handle a subgroup of the source files.

**Comment by hollowdoor** [comment]
@woodyrew Also they're filtered by frontmatter metadata right. Like the layout file to reference is referenced by:

---
layout: layout.html
---

For this usage it would be:

---
layout: layout.template
---

**Comment by woodyrew** [comment]
@hollowdoor Yes, a plugin can look at the file frontmatter too to make decisions.

**Comment by Ajedi32** [comment]
Basically yeah, each plugin determines for itself what files it can operate on.

If you want a more consistent filter, you could always use something like [`metalsmith-branch`](https://github.com/ericgj/metalsmith-branch), which works by splitting off a seperate pipeline containing only the matched files, running the specified plugins on that, then merging those changes back into the full files object.

**Comment by bitinn** [comment]
@Ajedi32 ah very cool, I saw it and didn't realize it was explicitly trying to solve my problem.

I think this can be closed, though I have [a tangentially related question](https://github.com/FWeinb/metalsmith-watch/issues/36) for `metalsmith-watch`, since it's not very well maintained, I appreciate if someone can give me some pointers.
