### ISSUE TITLE
Stuck in a catch 22 - Need list of processed files

### ISSUE THREAD

**Issue by jhyland87** [metalsmith/metalsmith#275]
Hello!

First off, just wanted to say this is a great library! I'm definitely enjoying working with it thus far.

Were working on a website that will contain an abundance of articles. Each article is a separate `source/articles/*.md` file, which will create an HTML file in `public/articles/*`. Then, I should be able to grab the list of HTML files in the `public/articles` directory to create links to each article.

I need the list of files that were successfully generated by Metalsmith so I can create a menu with links to each article. 

Is there a way around this "catch 22"? Perhaps a way to build just the content in `source/articles/*`, then I can insert another plugin to gather the list and hand it as metadata to the templates?

Thanks!

**Comment by jocelynlecomte** [comment]
You probably already use the collection and the permalink plugins by doing something like that:
```js
.use(collections({          // group all blog posts by internally
    articles: 'articles/*.md'       // adding key 'collections':'articles'
  }))
.use(permalinks()) // adds the path property to each article
```
In your template, you just need to do this to generate something for all the articles (I'll use Handlebars as my template engine):
```html
{{#each articles}}
  // here, this represents an article
  <a href="{{link this.path }}">{{ this.title }}</a>
{{/each}}
```

If you want more details, you could read the metalsmith home page or the serie of articles I wrote about the internals of metalsmith:  [A gentle introduction to Metalsmith](http://blog.lecomte.me/posts/2014/gentle-intro-metalsmith/metalsmith-for-masses/)

**Comment by thomas-williams** [comment]
How can this be done while insuring a specific order for the articles. I thought the `{#each articles}` would simply follow the order my markdown files appear in the folder, but it seems to be random every time I build the HTML files.

**Comment by webketje** [comment]
@thomas-williams as a workaround you can specify sortBy in [metalsmith-collections](https://github.com/segmentio/metalsmith-collections). You can mimic the file system order by setting the `sortBy: `  to 'slug' or 'path', if you use metalsmith-slug or have a plugin that sets the path,
