### ISSUE TITLE
Exposing multiple plugins by a single npm package

### ISSUE THREAD

**Issue by AndyOGo** [metalsmith/metalsmith#276]
I read through all the docs, but unfortunately export multiple plugins from a single npm package doesn't seem to be support.

It would be definetly no problem with the JS API, but CLI and `metalsmith.json` wouldn't work?

**Comment by Ajedi32** [comment]
Well, you could make the main plugin exposed by the package some kind of wrapper which selects one of the sub-plugins to use depending on what settings you pass it. E.g.:

```json
{
  "plugins": [
    {"metalsmith-superplugin": {
      "subplugin": "plugin x",
      "other_settings": {}
    }},
    {"metalsmith-superplugin": {
      "subplugin": "plugin y",
      "other_settings": {}
    }},
  ]
}
```

**Comment by AndyOGo** [comment]
@Ajedi32 
Thanks for your quick reply, meanwhile I thought about the same way.
Will close
