### ISSUE TITLE
Docs on the website: layout is not working

### ISSUE THREAD

**Issue by timaschew** [metalsmith/metalsmith#283]
On the website if I use all the snippets like below, the layout plugin is not working, it just transpiles the markdown to HTML, without the layour wrapper.

**index.js** 
```
var Metalsmith  = require('metalsmith');
var collections = require('metalsmith-collections');
var layouts     = require('metalsmith-layouts');
var markdown    = require('metalsmith-markdown');
var permalinks  = require('metalsmith-permalinks');


Metalsmith(__dirname)         // __dirname defined by node.js:
                              // name of current working directory
  .metadata({                 // add any variable you want
                              // use them in layout-files
    sitename: "My Static Site & Blog",
    siteurl: "http://example.com/",
    description: "It's about saying »Hello« to the world.",
    generatorname: "Metalsmith",
    generatorurl: "http://metalsmith.io/"
  })
  .source('./src')            // source directory
  .destination('./build')     // destination directory
  .clean(true)                // clean destination before
  .use(collections({          // group all blog posts by internally
    posts: 'posts/*.md'       // adding key 'collections':'posts'
  }))                         // use `collections.posts` in layouts
  .use(markdown())            // transpile all md into html
  .use(permalinks({           // change URLs to permalink URLs
    relative: false           // put css only in /css
  }))
  .use(layouts({              // wrap layouts around html
    engine: 'handlebars',     // use the layout engine you like
  }))
  .build(function(err) {      // build process
    if (err) throw err;       // error handling is required
  });
```

**my-file.md:**
```
---
title: A Catchy Title
draft: false
---

An unfinished article...
```

> Assuming somewhere amongst the source files we have defined a very simple standard handlebars layout file…

This is confusing and wrong, because _source files_ sounds like the _sourcepath_ which leads to making a page out of the layout. The layout MUST not be within the _sourcepath_.

You should mention to put the layout file next to `src` inside of a `layouts` directory and name it `default.html`.

**layouts/default.html** 
```
<!doctype html>
<html>
<head>
  <title>{{title}}</title>
</head>
<body>
  {{{contents}}}
</body>
</html>
```

This is still not working because the default layout is not be used by default, one of these actions needs to be done to get it working:

- put the `default.html` into the md files via front-matter
- add the `default` property to the `layouts()` handler, like this:
```
 .use(layouts({              // wrap layouts around html
    engine: 'handlebars',     // use the layout engine you like
    default: 'default.html'
  }))
```
- use CLI (but the docs are explaining already the API way not the CLI, so this is not really a solution) and the `metalsmith.json` and add this 
```
{
  "plugins": {
    "metalsmith-layouts": {
      "default": "default.html"
   }
}
```

**Comment by timaschew** [comment]
any feedback for this?

**Comment by Ajedi32** [comment]
I don't really have time to investigate this in detail right now, but at first glance it sounds like you're correct. If you want to send a PR to the [metalsmith.io repo](https://github.com/metalsmith/metalsmith.io) to fix these issues I'd gladly accept it.

**Comment by raulferras** [comment]
any updates on this? I can't find, even following @timaschew notes to make my  project to build

**Comment by ismay** [comment]
Actually layouts just had a major update. I can submit a PR to fix the example, or if someone else wants to do it in the meantime, the readme contains all necessary info: github.com/ismay/metalsmith-layouts

**Comment by itsMeBender** [comment]
When I follow the steps described in the README of github.com/ismay/metalsmith-layouts, It does not work!

Like using the CLI `node_modules/.bin/metalsmith` (not recognized).
So, I use `node node_modules/.bin/metalsmith`, which leads to:
`basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")  SyntaxError: missing ) after argument list `

**Comment by ismay** [comment]
@itsMeBender If you suspect something is broken, filing a pr with a breaking test or a repo with a minimal reproduction would be appreciated. For general help try the slack channel, where there’s always people who can help.

Posting that it doesn’t work in an unrelated issue isn’t really a good way to get help.

**Comment by ismay** [comment]
I think this issue can be closed btw, the example has been updated in #266

**Comment by itsMeBender** [comment]
I understand the need for a good description of the reported problem.
But I just followed the the README instructions, because

> the readme contains all necessary info: github.com/ismay/metalsmith-layouts

In the hope to pinpoint, my problems with Metalsmith. And I came to this issue, because of my problems concerning the layout. The problem is, that in order to write a PR, I need to know what exactly the problem is. The only thing I know, old version of Metalsmith is working, new version is not.
Is a version problem, a conflict with other modules, a configuration problem ... etc.
I need to investigate. But I'm new to Metalsmith and my journey starts with the documentation.

**Comment by ismay** [comment]
I understand. In that case creating a repository with a reproduction of the problem that’s as minimal as possible is a good starting point. That’ll help other people understand what’s going wrong. If you have that, post it in the slack channel and people can help.

If there turns out to be something wrong with the docs let me know and I’ll update them.

**Comment by webketje** [comment]
Closing as stale, feel free to provide updates if any.
