### ISSUE TITLE
Unhandled promise rejections are deprecated

### ISSUE THREAD

**Issue by KrishnaPG** [metalsmith/metalsmith#295]
Encountering this error:
````
(node:728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. 
In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````
It is coming from:
````
6:26:35 AM: (node:728) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): 
Error: ENOENT: no such file or directory, scandir '/opt/build/repo/app/company/content'
````
due to this code
````
module.exports = Metalsmith(__dirname)  
	.source(path.resolve(__dirname, '../app/company/content')) // source directory
````
the source path `../app/company/content` ofcourse doesn't exist. But the promise rejection should be gracefully handled and not let the node process crash (as the warning seem to indicate which would start to happen in the upcoming node versions).

PS: However, it is not clear if Metalsmith core can take care of this kind of promise rejections, or if user should do something about it.

**Comment by Ajedi32** [comment]
Yeah, looks like there may be some work to be done here. I suspect this would be fixed as a side-effect of switching Metalsmith to use a fully promise-based API, as I've been planning to do at some point in the future.

**Comment by Zearin** [comment]
@KrishnaPG Are you still having this issue?  

If so, can you tell us the following:
- your platform
- the output of running the following commands:
    - `npm --version`
    - `node --version`
    - `npm version` (should include the previous 2, as well as others; but the previous 2 are the most important, so I thought they deserved their own itemization ☻)

If you’re still getting this, I _might_ be able to roll out a fix myself in the near future.

**Comment by webketje** [comment]
ENOENT errors are now appropriately passed to build callback/ thenable
