### ISSUE TITLE
metalsmith.io vs metalsmith.github.io

### ISSUE THREAD

**Issue by jaredkrinke** [metalsmith/metalsmith#342]
Is there any reason there are two different sites for Metalsmith? I'm assuming metalsmith.io is the current one.

It was a little confusing when I randomly stumbled onto metalsmith.github.io and couldn't later find some of the content (e.g. link to RSS plugin) on the official site (which I know realize is a completely different domain!).

I'd suggest having the old site redirect to the new one.

**Comment by webketje** [comment]
@Ajedi32 ok to delete https://github.com/metalsmith/metalsmith.github.io ?

**Comment by Ajedi32** [comment]
Deleted. I assume we now have control of the build process for the main site?

**Comment by webketje** [comment]
@Ajedi32 Yes, with the IP assignment & domain name transfer complete a few weeks ago & the repositories transferred to the metalsmith org, I am only waiting for NPM publishing rights. I'm going full-speed this month as I will have a substantial amount of holiday time to dedicate to the project. How involved would you like to be? I make some announcements on https://gitter.im/metalsmith/community and am keeping ismay & woody posted perodically (though they haven't been responsive for the last 8mo.)

**Comment by Ajedi32** [comment]
Sounds good. I'm unlikely to be available for any significant level of involvement in the project these next few months, but wish you all the best.
