### ISSUE TITLE
metalsmith 2.4.0: index.js no longer published to npm in root folder

### ISSUE THREAD

**Issue by exortech** [metalsmith/metalsmith#364]
**Description**
After running `npm install`, running `require('metalsmith')` gives the error: `Error: Cannot find module 'metalsmith'` as index.js is no longer published in the root directory. Instead we need to run `require('metalsmith/lib')` to load metalsmith.

Issue with the latest version 2.4.0 published to npm.

Thanks for taking over the project btw!

**Comment by derrell** [comment]
Confirmed here too. The top-level `index.js` is missing, and gives an error when requiring metalsmith.

**Comment by webketje** [comment]
@derrell @exortech my sincere apologies and thank you for quickly bringing this to my attention. This has got to be the only thing that is not unit-testable from within the repo.
I am publishing a patch version ASAP

**Comment by webketje** [comment]
Republished with the missing index.js https://github.com/metalsmith/metalsmith/releases/tag/v2.4.1
