### ISSUE TITLE
Maintainer application

### ISSUE THREAD

**Issue by dpobel** [metalsmith/metalsmith#372]
Hello there :)

This is the follow up of https://github.com/metalsmith/rss/pull/8#issuecomment-1139499482 to start the process by the book :wink:  As mentioned there, I'm up to help on the rss plugin but actually I can help on others areas as well. (Initially I wanted to add a RSS feed to the website news)

I've been a user of Metalsmith for like 6 years (on [my personal blog](https://damien.pobel.fr/) mostly in :fr: also on some side project) and I'm super happy that it gets back to life!

I currently maintain 3 plugins:

1. https://github.com/dpobel/metalsmith-moment
1. https://github.com/dpobel/metalsmith-filemetadata
1. https://github.com/dpobel/metalsmith-pdfize

I would be happy to be integrated in the team and have push access but I can (and will) start with regular PR from forks anyway.

That's pretty much it I think. Cheers

**Comment by webketje** [comment]
Hi, welcome & thx for making the effort. I've put your plugins filemetadata & pdfize to good use before and contributed a feature to the former. I've given you access to the rss plugin & added you to the ideators team. If you would like additional accesses later we can discuss in that GH team or you can send me a message on Gitter. You're on my radar now so I will close this "issue" :smile:
