### ISSUE TITLE
drag and drop theme builder

### ISSUE THREAD

**Issue by linuxchico** [metalsmith/metalsmith#377]
Hi

I am looking for a website builder for static website. It's good that your project continues again.

Since I am very bad at coding my question:

Can you add a drag and drop theme builder?

Here is a tool for this:

[https://grapesjs.com/](url)

Here is a demo page:

[https://grapesjs.com/demo.html](url)

The code is here, but no longer up to date. In the issues you can still find the way:

[https://github.com/artf/grapesjs-preset-webpage](url)

It would be great if it worked!

**Comment by webketje** [comment]
Hi,
This is actually not such a bad idea for a plugin. The plugin would need to save the blocks in file metadata. @wernerglinka already went in that direction with "metalsmith components".

But it is outside of the scope of metalsmith.

**Comment by px-wernerglinka** [comment]
@[linuxchico](https://github.com/linuxchico) This not drag-and-drop but see for youself:  https://metalsmith-components.netlify.app/

**Comment by webketje** [comment]
Closing as stale & out of scope
