### ISSUE TITLE
Don't crash on broken symlinks that are ignored

### ISSUE THREAD

**Issue by zackw** [metalsmith/metalsmith#384]
**Description**

Metalsmith crashes if there's a broken symlink somewhere in the source directory, _even if_ the broken link's name matches an ignore pattern.  For example

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, stat '[REDACTED]/src/posts/foliomatic/.#index.md'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '[REDACTED]/src/posts/foliomatic/.#index.md'
}
```

This is the offending symlink:

```
lrwxrwxrwx  1 zack zack    27 Nov 25 19:58 .#index.md -> zack@moxana.2237:1669409078
```

It's an [Emacs lock file](https://www.gnu.org/software/emacs/manual/html_node/elisp/File-Locks.html#File-Locks).  Emacs (ab)uses the `symlink` system call as a way to create a file with specified contents in one atomic operation -- the destination of these symlinks is expected _never_ to exist.  They just mean "Emacs has unsaved changes to this file" (where "this file" is the file whose name you get by chopping the leading `.#` off the lockfile's name).

Metalsmith doesn't have to care about any of that, though.  What it _should_ care about is that I configured it to ignore files named `.#*` ...

```
Metalsmith(__directory)
    .source("src")
    .destination("build")
    .ignore([
      ".#*",
      "#*#",
      "*~",
      ".*.sw[a-p]",
    ])
   // ...
```

... and therefore _it should never have tried to stat any such file in the first place!_

I checked the code that processes ignore rules (https://github.com/metalsmith/metalsmith/blob/master/lib/helpers.js#L84) and it seems like you _are_ filtering out ignored files before _your_ first call to `stat`, but evidently that's not early enough.  I'd guess that either path.relative or path.resolve is calling stat internally, and I'd suggest finding an alternative API that does relative path computations _strictly via string manipulation_, without looking at the filesystem at all (if you don't mind looking at some Python documentation, see where https://docs.python.org/3/library/pathlib.html talks about the reasons to use "pure" paths instead of "concrete" paths).

**Environment**

- OS: linux
- Node v18.12.1
- npm v9.1.2
- Metalsmith v2.5.1

**Reproducing the bug**

This should be reproducible with the trivial Metalsmith configuration

```
const Metalsmith = require("metalsmith");

Metalsmith(__directory)
    .source("src")
    .destination("build")
    .ignore([
      ".#*",
    ])
   .build()
   .catch((err) => console.error(err));
```

Create a directory "src", put a file "index.md" in it.  Open that file in any vaguely recent version of Emacs (this locking strategy has been in use for more than 20 years).  Type a few lines of text.  **Without saving the file**, run `ls -l src` in another window to verify that a lockfile named `.#index.md` has been created, and then run Metalsmith.  You should see the crash.

**Comment by webketje** [comment]
This is .. intriguing.. I actually tested your suggestions (even installed emacs and followed the procedure you described at the bottom and saw the temp links appearing, node 18.12.1, MS 2.5.1)  and was so far unable to reproduce (except when non-ignored or using a function ignore)

I was going to ask "are you sure this is not sth. else in your plugin chain" but that's not possible.. unless maybe if you use a plugin like debug-ui which overwrites Metalsmith methods...

**Comment by zackw** [comment]
I _was_ using debug-ui, but I still see the problem even after commenting that out.  And, in fact, I still see the problem even if I cut _all_ of my plugins out, reducing it to the minimal example code I showed.  And if I add your suggested filelist check, it doesn't get a chance to execute.

I wonder if it matters that I'm in package.json `"type":"module"` mode.  Try that maybe?  With 

```
import Metalsmith from "metalsmith";
import * as url from "url";
const source_root = url.fileURLToPath(new URL(".", import.meta.url));
const ms = Metalsmith(source_root);
ms.source("src")
    .destination("build")
    .ignore([
      ".#*",
    ]);
await ms.build();
```

**Comment by webketje** [comment]
:facepalm: It's none of all we tried, and this is expected behavior.. I can't believe I looked past this. Good news is it's easy to fix (at the user's end). The description of the ignore method is 

> Get or set the list of filepaths or glob patterns to ignore

So evidently when `".#*"` is interpreted as file path it matches none, and when it is interpreted as glob, it matches only `.#filename.md` at the source root. To solve your use case you need the ignore `"**/.#*"` (= any number of subfolders). Tested locally and working :smile: 

micromatch does have a [basename option](https://github.com/micromatch/micromatch#optionsbasename) that allows glob patterns without slashes to match a file path based on its basename, but metalsmith.ignore is currently not configured with it/ does not provide access to its options (metalsmith.match does though)

**Comment by zackw** [comment]
You are correct. I assumed these worked like `.gitignore` patterns, i.e. "glob patterns without slashes [would] match a file path based on its basename".  Adding `**/` to the beginning of all the patterns fixes the problem for me.

It might be worth mentioning in the docs that these are matched using micromatch's default options.
